### ISSUE TITLE
Error: Exception in thread "main" java.lang.IllegalArgumentException: IDE must reside in a directory: /home/runner/.gradle/daemon/8.2/ides/IC-2023.2.2

### ISSUE THREAD

**Issue by PanPanZou** [JetBrains/intellij-platform-gradle-plugin#1516]
I use the template recommended:
```
verify:
    name: Verify plugin
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:

      - name: Maximize Build Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          large-packages: false
      - name: Fetch Sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-home-cache-cleanup: true
      - name: Setup Plugin Verifier IDEs Cache
        uses: actions/cache@v3
        with:
          path: ${{ needs.build.outputs.pluginVerifierHomeDir }}/ides
          key: plugin-verifier-${{ hashFiles('build/listProductsReleases.txt') }}
      - name: Run Plugin Verification tasks
        run: ./gradlew runPluginVerifier -Dplugin.verifier.home.dir=${{ needs.build.outputs.pluginVerifierHomeDir }}
      - name: Collect Plugin Verifier Result
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: pluginVerifier-result
          path: ${{ github.workspace }}/build/reports/pluginVerifier
``` 
but got an error: Error: Exception in thread "main" java.lang.IllegalArgumentException: IDE must reside in a directory: /home/runner/.gradle/daemon/8.2/ides/IC-2023.2.2.
Where https://github.com/JetBrains/intellij-plugin-verifier/releases/tag/v1.256 said that this issue has been fixed, but I still got this error.
